name = "cyberguard-api"
main = "worker.js"
compatibility_date = "2026-08-24"

[[d1_databases]]
binding = "DB"
database_name = "cyberguard-db"
database_id = "eff718ac-6868-423a-b2a5-bda1a8e6ce37"

[vars]
ENVIRONMENT = "production"
API_ORIGIN = "https://cyberguard-api.erenkaraca2005.workers.dev/"
